export const sectionToCrimeMap = {
  // IPC - Crimes Against Body
  "302": "MURDER",
  "307": "ATTEMPT TO MURDER",
  "304": "CULPABLE HOMICIDE NOT AMOUNTING TO MURDER",
  "304B": "DOWRY DEATHS",
  "306": "ABETMENT OF SUICIDE",
  "313": "CAUSING MISCARRIAGE WITHOUT WOMANS CONSENT",
  "323": "VOLUNTARILY CAUSING HURT",
  "324": "VOLUNTARILY CAUSING HURT BY DANGEROUS WEAPONS",
  "326": "VOLUNTARILY CAUSING GRIEVOUS HURT BY DANGEROUS WEAPONS",
  "363": "KIDNAPPING",
  "364": "KIDNAPPING FOR MURDER",
  "366": "KIDNAPPING & ABDUCTION OF WOMEN",

  // IPC - Crimes Against Property
  "379": "THEFT",
  "380": "THEFT IN DWELLING HOUSE",
  "384": "EXTORTION",
  "392": "ROBBERY",
  "395": "DACOITY",
  "396": "DACOITY WITH MURDER",
  "411": "DISHONESTLY RECEIVING STOLEN PROPERTY",
  "420": "CHEATING",
  "447": "CRIMINAL TRESPASS",
  "448": "HOUSE TRESPASS",
  "452": "HOUSE-TRESPASS AFTER PREPARATION FOR HURT",

  // IPC - Crimes Against Women/Children
  "354": "ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY",
  "376": "RAPE",
  "498A": "CRUELTY BY HUSBAND OR HIS RELATIVES",
  "509": "INSULT TO MODESTY OF WOMEN",
  "19": "CRIMES AGAINST CHILDREN", // Often mapped to POCSO or specific local acts

  // IPC - Public Order & Others
  "120B": "CRIMINAL CONSPIRACY",
  "143": "UNLAWFUL ASSEMBLY",
  "147": "RIOTING",
  "148": "RIOTING WITH DEADLY WEAPON",
  "153A": "PROMOTING ENMITY BETWEEN GROUPS",
  "279": "RASH DRIVING",
  "304A": "CAUSING DEATH BY NEGLIGENCE",
  "406": "CRIMINAL BREACH OF TRUST",
  "468": "FORGERY FOR PURPOSE OF CHEATING",
  "506": "CRIMINAL INTIMIDATION",
};
